### ISSUE TITLE
Is the dataset published now?

### ISSUE THREAD

**Issue by zhumorui** [zhu-xlab/M3R-CR#1]
As above question.

**Comment by LinpengPan** [comment]
As above question

**Comment by xufangchn** [comment]
Thanks for your interest in this work. The related paper is still under review and the dataset will be publicly available as soon as the paper is accepted.

**Comment by xufangchn** [comment]
For access to the complete dataset, kindly register at https://www.planet.com/markets/education-and-research/, and obtain the dataset link by contacting xufang@whu.edu.cn. Please note that M3M-CR is exclusively for academic research purposes.

**Comment by xufangchn** [comment]
For access to the complete dataset, kindly register at https://www.planet.com/markets/education-and-research/, and obtain the dataset link by contacting xufang@whu.edu.cn. Please note that M3M-CR is exclusively for academic research purposes.
