### ISSUE TITLE
Valuable Dataset Update: Enhancing Cloud Removal and Land Cover Classification

### ISSUE THREAD

**Issue by AbubkrSidiq** [zhu-xlab/M3R-CR#7]
Hi, Seeking an update on the availability of this highly valuable dataset, which has immense potential for advancing cloud removal techniques and refining land cover classification algorithms. It is a crucial resource for tasks pertaining to cloud removal and land cover classification. Could you please provide us with the latest update regarding its availability? Thanks

**Comment by AbubkrSidiq** [comment]
Hi, Could you please provide us with an update on the availability of the dataset? This dataset is highly valuable for tasks such as cloud removal and land cover classification. Thanks

**Comment by xufangchn** [comment]
For access to the complete dataset, kindly register at https://www.planet.com/markets/education-and-research/, and obtain the dataset link by contacting xufang@whu.edu.cn. Please note that M3M-CR is exclusively for academic research purposes.
